### ISSUE TITLE
Translate Error : 

### ISSUE THREAD

**Issue by HosseinKurd** [juniversal/juniversal#12]
Hi
When I want to Translate Java codes to Objective-C with Command inc Mac Termnal >>

```
java -jar juniversal/juniversal-translator/build/libs/juniversal-translator-0.8.3.jar -o $HOME/javaoutput/objectivec/testbuild -l objectivec -classpath  jsimple/libraries/jsimple-util/build/libs/jsimple-util-0.9.3.jar  -sourcepath $HOME/androidstudioprojects/testbuild/app/src/main/java  $HOME/androidstudioprojects/testbuild/app/src/test/java
```

Shows me error >>

```
Error: 'objectivec' is not a valid target language
```

I think it's Opening Ceremony Level :+1:

**Comment by BretJohnson** [comment]
The JUniversal translator doesn't support Objective-C output.  My plan to support iOS is via Swift and C++ output, though both are still work in progress, not complete enough yet to use.   At first, my thinking was support iOS via Objective C+, and the C++ support is mostly there, but since Swift 2 introduced exception handling (at least a form of it), that tilted the scales back to Swift.  I've been busy unfortunately & haven't gotten to spend much time on JUniversal recently, though really do want to get back to it.
As for Objectice-C output, Google's j2objc translator already does that, so probably best to stick with that.  You're welcome to use my Gradle wrapper to invoke j2objc (see directions at http://juniversal.org/getting-started) or the standalone Gradle wrapper for j2objc (see https://github.com/j2objc-contrib/j2objc-gradle) or invoke it directly.

**Comment by HosseinKurd** [comment]
I Have send Some Mail to you but no answer Recieved
If it Doesn't Work So Please Note Into Website About That
