### ISSUE TITLE
gradlew build install error on mac os yosemite

### ISSUE THREAD

**Issue by samuraisam** [juniversal/juniversal#2]
Trying to follow through the "getting started" guide on juniversal.org, running `./gradlew build install`.

System setup: Latest Mac OS X, Latest JDK

![screenshot 2015-02-04 11 03 41](https://cloud.githubusercontent.com/assets/101497/6046313/25e17358-ac5e-11e4-82fc-618226a8d14e.png)

**Comment by bret-johnson** [comment]
Thanks for the feedback.  That should be fixed now.   The intention is that (now) the signing only happens if the uploadArchives Gradle target is invoked, normally just done on the build machine, which has the signing key configured in the gradle.properties file.
Please holler when you run across other issues.
